apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-client
  template:
    metadata:
      labels:
        app: nexus-client
    spec:
      containers:
        - name: nexus-client
          image: 284698404434.dkr.ecr.us-east-1.amazonaws.com/nexus-client:1.0.0
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          ports:
            - containerPort: 80

